# Generated by Django 4.1.2 on 2022-10-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='parent',
        ),
    ]
