# Generated by Django 4.1.2 on 2022-10-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
    ]
